queue_rules:
  - name: default
    queue_conditions:
      - base=main
pull_request_rules:
  - name: label from branch
    conditions:
      - head=hunt-feature
    actions:
      label:
        add:
          - hunted
